### ISSUE TITLE
Error loading SlimeKnights at forge-14.23.5.2767 (and 2768)

### ISSUE THREAD

**Issue by VladimirMangos** [SlimeKnights/Mantle#110]
Crash report: https://paste.dimdev.org/surakenebo.mccrash

java.lang.Error: java.lang.reflect.InvocationTargetException
    at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
    at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
    at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Strange thing: it very similar to 2 year old issue #72

**Comment by VladimirMangos** [comment]
Look like this s problem at KnightMiner/Inspirations side https://github.com/KnightMiner/Inspirations/issues/89
