### ISSUE TITLE
EntityCamera cannot be cast to net.minecraft.entity.player.EntityPlayer

### ISSUE THREAD

**Issue by UltraCyberGod** [SlimeKnights/Mantle#111]
I'm posting though because I've developed a problem I cannot fix. I'm playing with the pixelmon reforged mod and better hud which is in beta. Up until 5 days ago it was fine when battling. From then on it crashes, it took quite a bit of time to work out which mod, but when I enable the health bar for better HUD mod and battle in pixelmon that's does it. I can have everything else on but that. Reports are below. I've tried with a fresh forge/optifine and just a couple of mods jei/nei/pixelmon/better hud and still get it on a fresh installation. I've downgraded from the java 191 back to 181 and 171. But get I've also dropped back the nvidia drivers from 416  to 411. From the look of it mantle may be responsible.

Can you help many thanks in advance UCG 

`java.lang.ClassCastException: com.pixelmonmod.pixelmon.client.camera.EntityCamera cannot be cast to net.minecraft.entity.player.EntityPlayer
at slimeknights.mantle.client.ExtraHeartRenderHandler.renderHealthbar(ExtraHeartRenderHandler.java:69)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_409_ExtraHeartRenderHandler_renderHealthbar_Pre.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at tk.nukeduck.hud.element.vanilla.OverrideElement.shouldRender(OverrideElement.java:26)
at tk.nukeduck.hud.element.vanilla.Bar.shouldRender(Bar.java:41)
at tk.nukeduck.hud.element.vanilla.HealthBar.shouldRender(HealthBar.java:40)
at tk.nukeduck.hud.element.HudElement.tryRender(HudElement.java:227)
at tk.nukeduck.hud.element.HudElement.renderAll(HudElement.java:252)
at tk.nukeduck.hud.events.RenderEvents.onRenderTick(RenderEvents.java:79)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_293_RenderEvents_onRenderTick_Pre.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:119)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1420)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by bonii-xx** [comment]
That does indeed look like a bug. The code doesn't expect anything but players to be the entity in control. Might be an overlook or simply old code where that was true (the original code is pretty old).
