### ISSUE TITLE
1.12.2 crash - BlockLiquidSlime / BlockMolten

### ISSUE THREAD

**Issue by TheUppityCow** [SlimeKnights/Mantle#123]
I have been playing with Tinkers Construct for a few weeks and added a few new mods and now it won't load. If I remove Mantle and Tinkers, the game loads fine but the server I used includes it so it's necessary I have them. Also, if I remove Mantle, the game doesn't crash but just says I need Mantle to run Tinkers. If I then add Mantle back, the game just crashes on the initialization screen for Minecraft. It cycles between a few different errors that show when the game crashes.

Minecraft - 1.12.2
Forge - 1.12.2-14.23.5.2772
Mantle - 1.12-1.3.3.55.jar
TConstruct - 1.12.2-2.12.0.157.jar
Mods on my computer -

<img width="196" alt="Screen Shot 2019-07-21 at 2 13 40 PM" src="https://user-images.githubusercontent.com/53152684/61595849-dc071400-abc1-11e9-8d03-20d39df546c7.png">

***1st error report***
vvvvvvvvv
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: slimeknights/tconstruct/shared/block/BlockLiquidSlime

***2nd error report***
vvvvvvvvv
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: slimeknights/tconstruct/smeltery/block/BlockMolten

<img width="553" alt="Screen Shot 2019-07-21 at 2 12 06 PM" src="https://user-images.githubusercontent.com/53152684/61595814-8df21080-abc1-11e9-8a66-c032db6562b5.png">

Detailed Crash Report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  SpongeCoremod (spongeforge-1.12.2-2825-7.1.6.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 7/21/19 2:11 PM
Description: Initializing game

java.lang.NoClassDefFoundError: slimeknights/tconstruct/shared/block/BlockLiquidSlime
	at slimeknights.tconstruct.TConstruct.<clinit>(TConstruct.java:108)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.shared.block.BlockLiquidSlime
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: slimeknights/tconstruct/smeltery/block/BlockTinkerFluid
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.smeltery.block.BlockTinkerFluid
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at slimeknights.tconstruct.TConstruct.<clinit>(TConstruct.java:108)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 382736152 bytes (365 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 Optifine OptiFine_1.12.2_HD_U_E2 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                  | Source                                               | Signature                                |
	|:----- |:--------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft       | 1.12.2                   | minecraft.jar                                        | None                                     |
	| UC    | mcp             | 9.42                     | minecraft.jar                                        | None                                     |
	| UC    | FML             | 8.0.99.99                | forge-1.12.2-14.23.5.2772.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge           | 14.23.5.2772             | forge-1.12.2-14.23.5.2772.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | spongeapi       | 7.1.0-fb496dbf0          | spongeforge-1.12.2-2825-7.1.6.jar                    | None                                     |
	| UC    | sponge          | 1.12.2-7.1.6             | spongeforge-1.12.2-2825-7.1.6.jar                    | None                                     |
	| UC    | spongeforge     | 1.12.2-2825-7.1.6        | spongeforge-1.12.2-2825-7.1.6.jar                    | None                                     |
	| UC    | zawa            | 1.12.2-1.6.0             | zawa+-+1.6.0+(1.12.2).jar                            | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| UC    | bookworm        | 1.12.2-2.2.0             | bookworm+-+2.2.0+(1.12.2).jar                        | None                                     |
	| UC    | ctm             | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                            | None                                     |
	| UC    | chisel          | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| UC    | craftstudioapi  | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar   | None                                     |
	| UC    | elevatorid      | 1.3.10                   | ElevatorMod-1.12.2-1.3.10.jar                        | None                                     |
	| UC    | inventorytweaks | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironbackpacks   | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                    | None                                     |
	| UC    | jei             | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                            | None                                     |
	| UC    | journeymap      | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                          | None                                     |
	| UC    | mantle          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| UC    | harvestcraft    | 1.12.2zb                 | Pam_s+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None                                     |
	| UC    | ropebridge      | 2.0.5                    | ropebridge-1.12-2.0.7.jar                            | None                                     |
	| U     | tconstruct      | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                     | None                                     |
	| U     | xaerominimap    | 1.17.3                   | Xaeros_Minimap_1.17.3_Forge_1.12.jar                 | None                                     |
	| U     | llibrary        | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                           | None                                     |
	| U     | jurassicraft    | 2.1.23                   | JurassiCraft-1.12.2-2.1.23.jar                       | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
SpongeCoremod (spongeforge-1.12.2-2825-7.1.6.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-2.9.26' Renderer: 'AMD Radeon Pro 560 OpenGL Engine'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2772
	LWJGL: 2.9.2
	OpenGL: AMD Radeon Pro 560 OpenGL Engine GL version 2.1 ATI-2.9.26, ATI Technologies Inc.
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,sponge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz

**Comment by bonii-xx** [comment]
You have a coremod breaking things. TiC is just the first mod where it is noticed.

**Comment by KnightMiner** [comment]
Closing for lack of information, as its likely a coremod breaking things
