### ISSUE TITLE
[InvocationTargetException]: java.lang.Error: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Lanse505** [SlimeKnights/Mantle#62]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Pong ASM (Pong-1.9.4-1.0.0.1-universal.jar)
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.1.1.jar)
  FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  LoadingPlugin (LoadingProfiler-MC1.9.4-1.3.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  Reborn Core ASM (RebornCore-1.9.4-2.4.3.32-universal.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
  CXLibraryCore (cxlibrary-1.1.0-1.9.4.jar)
  CorePlugin (WorldSelectionAdvanced-1.9.4-01.jar)
  BetterMinecraftChat (BetterMinecraftChat-mc1.9.4-2.0.5.jar)
  BetterFontsCore (TTFR-1.4.0-1.9.4.jar)
  MDECore-Core (mdecore-1.9.4-1.0.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 2016-06-01 20:40
Description: Initializing game

java.lang.Error: java.lang.reflect.InvocationTargetException
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:587)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:89)
	... 33 more
Caused by: java.lang.NullPointerException
	at slimeknights.tconstruct.library.MaterialIntegration.integrate(MaterialIntegration.java:61)
	at slimeknights.tconstruct.TinkerIntegration.preInit(TinkerIntegration.java:93)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:587)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 444541608 bytes (423 MB) / 1748500480 bytes (1667 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.28 Powered by Forge 12.17.0.1937 97 mods loaded, 96 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1937.jar) 
	UCH	Forge{12.17.0.1937} [Minecraft Forge] (forge-1.9.4-12.17.0.1937.jar) 
	UCH	BetterFonts{1.4.0} [BetterFonts] (minecraft.jar) 
	UCH	actuallyadditions{1.9.4-r36} [Actually Additions] (ActuallyAdditions-1.9.4-r36.jar) 
	UCH	mdecore{1.9.4-1.0} [MattDahEpic Core] (mdecore-1.9.4-1.0.jar) 
	UCH	autooredictconv{1.9.4-1.0} [Auto Ore Dictionary Converter] (autooredictconv-1.9.4-1.0.jar) 
	UCH	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCH	BaublesHud{3.0.0} [Baubles-Hud] (BaublesHud-1.9.4-3.0.0.jar) 
	UCH	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCH	BetterAchievements{0.2.5.24} [Better Achievements] (BetterAchievements-1.9.4-0.2.5.24.jar) 
	UCH	betterminecraftchat{2.0.5} [BetterMinecraftChat] (BetterMinecraftChat-mc1.9.4-2.0.5.jar) 
	UCH	BiomesOPlenty{4.1.0.2023} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2023-universal.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.9.4-alpha-1.0.0.jar) 
	UCH	JEI{3.4.2.206} [Just Enough Items] (jei_1.9.4-3.4.2.206.jar) 
	UCH	BloodMagic{1.9.4-2.0.1-40} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.1-40.jar) 
	UCH	bookshelf{1.2.2.254} [Bookshelf] (Bookshelf-1.9.4-1.2.2.256.jar) 
	UCH	Chameleon{1.9-2.1.4} [Chameleon] (Chameleon-1.9-2.1.4.jar) 
	UCH	chiselsandbits{10.2} [Chisels & Bits] (chiselsandbits-10.2.jar) 
	UCH	ChunkAnimator{1.1.1} [Chunk Animator] (ChunkAnimator-MC1.9.4-1.1.1.jar) 
	UCH	clayworldgen{1.1.0} [Clay WorldGen] (ClayWorldGen-1.1.0-1.9.4.jar) 
	UCH	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9.4.jar) 
	UCH	cookingforblockheads{3.0.7} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.0.7.jar) 
	UCH	craftingtweaks{5.0.6} [Crafting Tweaks] (craftingtweaks-mc1.9.4-5.0.6.jar) 
	UCH	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.9.4-2.0.jar) 
	UCH	cxlibrary{1.1.0} [CXLibrary] (cxlibrary-1.1.0-1.9.4.jar) 
	UCH	cyclopscore{0.6.3} [Cyclops Core] (CyclopsCore-1.9.4-0.6.3.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	DarkUtils{1.1.1.42} [Dark Utilities] (DarkUtilities-1.9.4-1.1.1.43.jar) 
	UCH	ElecCore{1.5.285} [ElecCore] (ElecCore-1.9.4-1.5.285.jar) 
	UCH	deepresonance{1.1.4beta32} [DeepResonance] (deepresonance-1.9.4-1.1.4beta32.jar) 
	UCH	enchiridion{3.1.2} [Enchiridion] (Enchiridion-1.9.4-3.1.2.jar) 
	UCH	endercore{1.9.4-0.4.0.23-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.23-alpha.jar) 
	UCH	EnderIO{1.9.4-3.0.0.36_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.36_alpha.jar) 
	UCH	EnderZoo{1.9.4-1.2.2.40} [Ender Zoo] (EnderZoo-1.9.4-1.2.2.40.jar) 
	UCH	ExtraBitManipulation{1.9-2.1.2} [Extra Bit Manipulation] (ExtraBitManipulation-1.9.4-2.1.0.jar) 
	UCH	FFS{1.9.4-1.5.5-b15} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9.4-1.5.5-b15.jar) 
	UCH	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-MC1.9.4-1.7.jar) 
	UCH	fluxducts{1.0.4} [Flux Ducts] (fluxducts-mc1.9.4-1.0.4.jar) 
	UCH	furnus{1.80} [Furnus] (Furnus-1.9.4-1.80.jar) 
	UCH	gearswap{1.2.6} [Gear Swapper] (gearswap-1.9.4-1.2.6.jar) 
	UCH	combat{1.0.0} [Gladius] (Gladius-1.2.0.jar) 
	UCH	Harvest{1.9.4-1.0.1-5} [Harvest] (Harvest-1.9.4-1.0.1-5.jar) 
	UCH	HelpFixer{1.3.14} [HelpFixer] (HelpFixer-1.9.4-1.3.14.jar) 
	UCH	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7.jar) 
	UCH	integrateddynamics{0.3.10} [Integrated Dynamics] (IntegratedDynamics-1.9.4-0.3.10.jar) 
	UCH	inventorytweaks{1.61-dev-53-0736dc3} [Inventory Tweaks] (InventoryTweaks-1.61-dev-53.jar) 
	UCH	IronChest{6.0.141.782} [Iron Chest] (ironchest-1.9.4-6.0.141.782.jar) 
	UCH	journeymap{1.9.4-5.2.0} [JourneyMap] (journeymap-1.9.4-5.2.0-unlimited.jar) 
	UCH	jeresources{0.4.5.31} [Just Enough Resources] (JustEnoughResources-1.9.4-0.4.5.31.jar) 
	UCH	LoadingProfiler{1.1} [Loading Profiler] (LoadingProfiler-MC1.9.4-1.3.jar) 
	UCH	LunatriusCore{1.1.2.35} [LunatriusCore] (LunatriusCore-1.9.4-1.1.2.35-universal.jar) 
	UCH	mantle{1.9.4-0.10.1.jenkins142} [Mantle] (Mantle-1.9.4-0.10.1.jenkins142.jar) 
	UCH	MapWriter{2.5.19} [MapWriter] (MapWriter-1.9.4-2.5.19.jar) 
	UCH	minemenu{1.4.3} [MineMenu] (MineMenu-1.9.X-1.4.3.B6-universal.jar) 
	UCH	testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCH	moreoverlays{1.3} [MoreOverlays] (moreoverlays-1.3-mc1.9.4.jar) 
	UCH	Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool] (Morph-o-Tool-1.0-2.jar) 
	UCH	Morpheus{1.9.4-3.1.3} [Morpheus] (Morpheus-1.9.4-3.1.3.jar) 
	UCH	MouseTweaks{2.6.3} [Mouse Tweaks] (MouseTweaks-2.6.3-mc1.9.4.jar) 
	UCH	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-8.jar) 
	UCH	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCH	recipehandler{0.4} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.4(1.9).jar) 
	UCH	NotEnoughCodecs{0.5} [NotEnoughCodecs] (NotEnoughCodecs-0.5.jar) 
	UCH	notenoughwands{1.3.4} [Not Enough Wands] (notenoughwands-1.9.4-1.3.4.jar) 
	UCH	oretweaker{1.0.0} [Ore Tweaker] (OreTweaker-1.0.0-1.9.4.jar) 
	UCH	packingtape{0.5.1} [Packing Tape] (PackingTape-1.9.4-0.5.1.jar) 
	UCH	PotionIcons{1.9.4} [PotionIcons] (potionicons-1.9.4-1.0.0-release.jar) 
	UCH	progressiveautomation{1.6.46} [Progressive Automation] (ProgressiveAutomation-1.9.4-1.6.46.jar) 
	UCH	Psi{beta-33} [Psi] (Psi-beta-33.jar) 
	UCH	quantumflux{2.0.6} [QuantumFlux] (quantumflux-1.9.4-2.0.6.jar) 
	UCH	Quark{beta-21} [Quark] (Quark-beta-21.jar) 
	UCH	RandomUtilities{3.1.0} [Random Utilities] (Random Utilities-1.9.4-3.1.0.jar) 
	UCH	randomthings{3.7.3} [Random Things] (RandomThings-MC1.9.4-3.7.3.jar) 
	UCH	reborncore{2.4.3.32} [RebornCore] (RebornCore-1.9.4-2.4.3.32-universal.jar) 
	UCH	refinedstorage{0.7.6} [Refined Storage] (refinedstorage-0.7.6.jar) 
	UCH	xreliquary{1.9.4-1.3.2.372} [Reliquary] (Reliquary-1.9.4-1.3.2.372.jar) 
	UCH	ResourceLoader{1.5} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.jar) 
	UCH	rftools{4.50} [RFTools] (rftools-1.9.4-4.50.jar) 
	UCH	rftoolsdim{4.23beta40} [RFTools Dimensions] (rftoolsdim-1.9.4-4.23beta40.jar) 
	UCH	sensorcraft{0.3.0} [SensorCraft] (sensorcraft-0.3.0-1.9.4.jar) 
	UCH	shadowmc{3.3.6} [ShadowMC] (ShadowMC-1.9.4-3.3.6.jar) 
	UCH	SleepingBag{1.2.0} [Sleeping Bag] (SleepingBag-1.9.4-1.2.0.jar) 
	UCH	Stackie{1.6.0.42} [Stackie] (Stackie-1.9.4-1.6.0.42-universal.jar) 
	UCH	StorageDrawers{1.9-3.1.7} [Storage Drawers] (StorageDrawers-1.9-3.1.7.jar) 
	UC	tconstruct{1.9.4-2.3.1.jenkins229} [Tinkers' Construct] (TConstruct-1.9.4-2.3.1.jenkins229.jar) 
	UC	techreborn{1.2.3.76} [TechReborn] (TechReborn-1.9.4-1.2.3.76-universal.jar) 
	UC	tis3d{0.9.0.5} [TIS-3D] (TIS-3D-MC1.9.4-0.9.0.5.jar) 
	UC	torcherino{1.9.4-2.4.0} [Torcherino] (Torcherino-TehNut-1.9.4-2.4.0.jar) 
	UC	trashslot{5.0.7} [TrashSlot] (trashslot-mc1.9.4-5.0.7.jar) 
	UC	wailafeatures{0.3.1.10} [WAILA-features] (WAILA-features-1.9.4-0.3.1.10.jar) 
	UC	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	UC	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9.4-2.2.1.189.jar) 
	UC	wawla{2.2.1.188} [What Are We Looking At] (Wawla-1.9.4-2.2.1.189.jar) 
	UC	Woot{1.9.4-0.1.0-beta} [Woot] (woot-1.9.4-0.1.0-beta.jar) 
	UC	WorldSelectionAdvanced{1.9.4-01} [Advanced World Selection] (WorldSelectionAdvanced-1.9.4-01.jar) 
	UD	mdecore-core{1.0} [MDE Core - ASM Tweaks] (minecraft.jar) 
	Loaded coremods (and transformers): 
Pong ASM (Pong-1.9.4-1.0.0.1-universal.jar)
  me.modmuss50.pong.PongClassTransformer
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (ChunkAnimator-MC1.9.4-1.1.1.jar)
  lumien.chunkanimator.asm.ClassTransformer
FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (LoadingProfiler-MC1.9.4-1.3.jar)
  lumien.loadingprofiler.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  invtweaks.forge.asm.ContainerTransformer
Reborn Core ASM (RebornCore-1.9.4-2.4.3.32-universal.jar)
  reborncore.asm.RebornClassTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CXLibraryCore (cxlibrary-1.1.0-1.9.4.jar)
  cubex2.cxlibrary.CoreModTransformer
CorePlugin (WorldSelectionAdvanced-1.9.4-01.jar)
  sedridor.worldselectionadvanced.core.Transformer
BetterMinecraftChat (BetterMinecraftChat-mc1.9.4-2.0.5.jar)
  net.blay09.mods.bmc.coremod.ClassTransformer
BetterFontsCore (TTFR-1.4.0-1.9.4.jar)
  cubex2.ttfr.BFClassTransformer
MDECore-Core (mdecore-1.9.4-1.0.jar)
  com.mattdahepic.mdecore.asm.TickrateTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13431 Compatibility Profile Context 16.150.2211.0' Renderer: 'AMD Radeon R9 200 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Launched Version: forge-12.17.0.1937
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.13431 Compatibility Profile Context 16.150.2211.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: net.minecraft.client.Minecraft$15@57b2d262

**Comment by Lanse505** [comment]
Caused by and Fixed By Updating Extra Utilties (not sure why though).
