### ISSUE TITLE
Error loading SlimeKnights

### ISSUE THREAD

**Issue by PretoAlbino** [SlimeKnights/Mantle#72]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.1.148-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.2.1.80-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  CCCDeobfPlugin (unknown)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.0.44-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.3.1.88-universal.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 10/9/16 1:54 AM
Description: Initializing game

java.lang.Error: java.lang.reflect.InvocationTargetException
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:609)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:89)
	... 41 more
Caused by: java.lang.NullPointerException
	at slimeknights.tconstruct.shared.TinkerCommons.preInit(TinkerCommons.java:329)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:609)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 637289000 bytes (607 MB) / 1477967872 bytes (1409 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3072m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2097 Optifine OptiFine_1.10.2_HD_U_C3 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2097-universal.jar) 
	UCH	Forge{12.18.2.2097} [Minecraft Forge] (forge-1.10.2-12.18.2.2097-universal.jar) 
	UCH	CodeChickenCore{2.2.1.80} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{2.1.1.148} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.1.148-universal.jar) 
	UCH	backpack{3.0.1} [Backpack] (backpack-3.0.1-1.10.2.jar) 
	UCH	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCH	BaublesHud{3.0.0} [Baubles-Hud] (BaublesHud-1.9.4-3.0.0.jar) 
	UCH	bdlib{1.12.2.8} [BD Lib] (bdlib-1.12.2.8-mc1.10.2.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCH	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UC	tconstruct{1.10.2-2.5.1.jenkins349} [Tinkers' Construct] (TConstruct-1.10.2-2.5.1.jar) 
	UC	immersiveengineering{0.10-41} [Immersive Engineering] (ImmersiveEngineering-0.10-41.jar) 
	UC	JEI{3.12.6.304} [Just Enough Items] (jei_1.10.2-3.12.6.304.jar) 
	UC	BloodMagic{1.9.4-2.1.0-65} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-65 (1).jar) 
	UC	Botania{r1.9-325} [Botania] (Botania r1.9-325.jar) 
	UC	brandonscore{2.1.0} [Brandon's Core] (BrandonsCore-1.10.2-2.1.0.44-universal.jar) 
	UC	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UC	ChickenChunks{2.1.4.38} [ChickenChunks] (ChickenChunks-1.10.2-2.1.4.38-universal.jar) 
	UC	chisel{MC1.9.4-0.0.6.42} [Chisel] (Chisel-MC1.9.4-0.0.6.42.jar) 
	UC	craftingtweaks{6.1.14} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.14.jar) 
	UC	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UC	draconicevolution{2.0.0} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.0.100-universal.jar) 
	UC	endercore{1.10.2-0.4.1.55-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.55-beta.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UC	EnderIO{1.10.2-3.0.1.110_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.110_beta.jar) 
	UC	EnderStorage{2.1.4.77} [EnderStorage] (EnderStorage-1.10.2-2.1.4.77-universal.jar) 
	UC	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.1.0a.jar) 
	UC	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.2.jar) 
	UC	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UC	LunatriusCore{1.1.2.36} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
	UC	harvestcraft{1.9.4-1.10.2e} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2e.jar) 
	UC	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UC	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UC	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UC	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UC	Translocator{2.1.2.30} [Translocator] (Translocators-1.10.2-2.1.2.30-universal.jar) 
	UC	WailaHarvestability{1.1.8} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.8.jar) 
	UC	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.10.2-2.1.1.148-universal.jar)
  codechicken.nei.asm.NEITransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.2.1.80-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
CCCDeobfPlugin (unknown)
  
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
DepLoader (BrandonsCore-1.10.2-2.1.0.44-universal.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.3.1.88-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13447 Compatibility Profile Context 20.19.0.32837' Renderer: 'AMD Radeon R7 200 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	CodeChickenCore: ignoreInvalidMCVersion state: false
	List of loaded APIs: 
		* Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.1.0-65 (1).jar
		* BotaniaAPI (81) from Botania r1.9-325.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.6.42.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.6.42.jar
		* CoFHAPI (1.8.9R1.2.0B1) from BrandonsCore-1.10.2-2.1.0.44-universal.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from BrandonsCore-1.10.2-2.1.0.44-universal.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.10.2-6.1.14.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.10.2-2.0.0.100-universal.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.110_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.110_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.110_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.110_beta.jar
		* Guide-API|API (1.10.2-2.0.2-45) from Guide-API-1.10.2-2.0.2-45.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-41.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-41.jar
		* JustEnoughItemsAPI (4.9.0) from jei_1.10.2-3.12.6.304.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: AMD Radeon R7 200 Series GL version 4.5.13447 Compatibility Profile Context 20.19.0.32837, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Unity-1.3.1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13447 Compatibility Profile Context 20.19.0.32837
	OpenGlRenderer: AMD Radeon R7 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by 63502** [comment]
I think I can confirm this. 
It appears to only happen with Forge version 12.18.2.2097 atm.

[Crash Report](https://gist.github.com/63502/1258a43fd535355f15abeb03067dfc51)

**Comment by bonii-xx** [comment]
Does 2098 fix the issue?

**Comment by PretoAlbino** [comment]
I Will test, 2098 was released today

**Comment by bonii-xx** [comment]
I just tested, 2098 fixes the issue. Guess it'll be recommended too, then, once lex is around.

**Comment by PretoAlbino** [comment]
Ok thanks
